
hide footbox

!define BGCOLOR #DADADA
!define ACTORBGCOLOR #CCCCCC
!define ARROWCOLOR #444444
!define BORDERCOLOR #222222
!define TEXTCOLOR #000000

skinparam class {
	BackgroundColor BGCOLOR
	ArrowColor ARROWCOLOR
	BorderColor BORDERCOLOR
}

skinparam interface {
	BackgroundColor BGCOLOR
	ArrowColor ARROWCOLOR
	BorderColor BORDERCOLOR
}

skinparam component {
	BackgroundColor BGCOLOR
	ArrowColor ARROWCOLOR
	BorderColor BORDERCOLOR
}

skinparam object {
	BackgroundColor BGCOLOR
	ArrowColor ARROWCOLOR
	BorderColor BORDERCOLOR
}

skinparam classAttributeIconSize 0
skinparam objectAttributeIconSize 0

skinparam sequence {
	ArrowColor ARROWCOLOR
	ActorBorderColor BORDERCOLOR
	LifeLineBorderColor #666666
	LifeLineBackgroundColor BGCOLOR

	ParticipantBorderColor BORDERCOLOR
	ParticipantBackgroundColor BGCOLOR
	ParticipantFontName Impact
	ParticipantFontSize 12
	ParticipantFontColor TEXTCOLOR

	ActorBackgroundColor ACTORBGCOLOR
	ActorFontColor TEXTCOLOR
	ActorFontSize 12
	ActorFontName Aapex
}
